import { jsonError, jsonOk, readJsonBody } from "@/lib/api";
import { taskRepository } from "@/lib/repository";
import { toTaskWithOverdue } from "@/lib/tasks";
import { validateUpdateTask } from "@/lib/validation";

// `RouteContext<'/api/tasks/[id]'>` is a global helper generated by `next typegen`,
// `next dev` or `next build`. It types `params` from the route path.
type TaskRouteContext = RouteContext<"/api/tasks/[id]">;

/** GET /api/tasks/:id — fetch a single task. */
export async function GET(_request: Request, context: TaskRouteContext) {
  const { id } = await context.params;
  const task = taskRepository.findById(id);

  if (!task) return jsonError(404, "Task not found");

  return jsonOk({ task: toTaskWithOverdue(task) });
}

/**
 * PATCH /api/tasks/:id — edit a task. Also used to mark a task complete or
 * incomplete by sending `{ "completed": true }`.
 */
export async function PATCH(request: Request, context: TaskRouteContext) {
  const { id } = await context.params;

  const existing = taskRepository.findById(id);
  if (!existing) return jsonError(404, "Task not found");

  const body = await readJsonBody(request);
  if (!body.ok) return jsonError(400, body.error);

  const result = validateUpdateTask(body.value);
  if (!result.ok) return jsonError(400, result.error);

  const task = taskRepository.update(id, result.value);
  if (!task) return jsonError(404, "Task not found");

  return jsonOk({ task: toTaskWithOverdue(task) });
}

/** DELETE /api/tasks/:id — delete a task. */
export async function DELETE(_request: Request, context: TaskRouteContext) {
  const { id } = await context.params;
  const removed = taskRepository.remove(id);

  if (!removed) return jsonError(404, "Task not found");

  return jsonOk({ deleted: true, id });
}
